name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  

      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=my_project tests/ 

      - name: Upload coverage results to codecov
        uses: codecov/codecov-action@v3 
        with:
          token: ${{ secrets.CODECOV_TOKEN }} 

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for SuperLinter
        uses: actions/setup-node@v3
        with:
          node-version: '16' 
