name: CI Pipeline for Unit Tests

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: "Downloading repository"
      uses: actions/checkout@v3

    - name: "Set up Python"
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: "Install dependencies"
      run: |
        pip install -r requirements.txt 
        pip install pytest-cov  
        
    - name: "Run tests with coverage"
      run: pytest -vv --cov=task1 tests

  linter:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write
      statuses: write

    steps:
      - name: "Downloading repository"
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: "Install dependencies"
        run: |
          pip install -r requirements.txt 
          pip install ruff

      - name: "Cache super-linter"
        uses: actions/cache@v3
        with:
          path: .cache/super-linter
          key: ${{ runner.os }}-super-linter-${{ hashFiles('**/*.py') }} # Cache the linter to speed up the process after the first run
          restore-keys: |
            ${{ runner.os }}-super-linter-

      - name: "Super-Linter"
        uses: super-linter/super-linter/slim@v7.1.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_RUFF: true
          CACHE_DIR: .cache/super-linter
          OUTPUT_DETAILS: log


      - name: "Run Ruff Formatter (Check mode)"
        id: ruff_check
        run: |
          ruff format --diff --check .
        continue-on-error: true


      - name: "Run Ruff Formatter (Fix mode)"
        if: ${{ steps.ruff_check.outcome == 'failure' }}
        run: |
          ruff format .

      - name: "Commit and push changes"
        if: ${{ steps.ruff_check.outcome == 'failure' }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Automated code formatting by Ruff"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.head_ref }}
  

  todo_to_issue:
    needs: linter
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        with:
          INSERT_ISSUE_URLS: "true"
          CLOSE_ISSUES: 'true'
          AUTO_ASSIGN: 'true'
      - name: Set Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and Push Changes
        run: |
          git add -A
          if [[ `git status --porcelain` ]]; then
            git commit -m "Automatically added GitHub issue links to TODOs"
            git push origin main
          else
            echo "No changes to commit"
          fi